create table registrations (
  id bigint generated by default as identity primary key,
  created_at timestamp without time zone default now() not null,
  device_library_identifier text not null,
  serial_number bigint not null,

  unique(device_library_identifier)
);
