create type platform as enum ('Apple', 'Google');
create table downloads (
  id bigint generated by default as identity primary key,
  time_of_download timestamp without time zone default now() not null,
  platform platform not null,
  template_version int not null,
  passport_id bigint not null,
  issue_date timestamp without time zone not null,
  address text not null,
  ens_name text
);
