create table latest_updates (
  id bigint generated by default as identity primary key,
  time timestamp without time zone default now() not null,
  title text not null,
  content text not null
);
insert into latest_updates (title, content) values ('N3GOV-16: All governance proposals must explain how they help advance the North Star metrics', 'This is very self-descriptive, but it''s a nice add-on to Proposal: Set Nation3''s North Star metrics. We have seen too many times how DAOs end up with endless bureaucracy because there''s no room for execution amidst chaos and uncertainty. Therefore having a unified set of metrics to advance, and making all governance proposals adhere to advancing them, makes sense. This is the pull request to the governance proposals repo, and this is the specific change.')
